### ISSUE TITLE
[Linux]  The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by raveltan** [wattry/vim-adventures#22]
Error when running on linux, 
After changing the file permission, i run the binary.

but it produces an error,

it provides this output:
```bash
pkg/prelude/bootstrap.js:1244
      throw error;
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.resolve (path.js:980:7)
    at Object.<anonymous> (/snapshot/vim-adventures/src/routes/index.js:13:22)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:77:18) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
Any suggestion about what have i done wrong?

**Comment by wattry** [comment]
That looks like the path to the saved directory has not been correctly setup.

**Comment by raveltan** [comment]
Okay, i've found the problem, the env file is misplaced, thank you
